# Generated by Django 3.2 on 2022-05-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MN', 'Основной'), ('AD', 'Дополнительный'), ('CH', 'По уходу за ребёнком'), ('NP', 'Не оплачиваемый'), ('ST', 'На учёбу')], default='MN', max_length=2, verbose_name='Тип отпуска')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата конца')),
                ('is_pay_now', models.BooleanField(verbose_name='Выплатить отпускные сейчас')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(blank=True, choices=[('OA', 'На согласовании'), ('RE', 'Отклонено'), ('AC', 'Согласовано')], default='OA', max_length=2, verbose_name='Статус')),
            ],
        ),
    ]
