# Generated by Django 3.2 on 2022-04-25 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('patronymic', models.CharField(max_length=32)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.position')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MN', 'Main'), ('AD', 'Additional'), ('CH', 'Child care'), ('NP', 'Not paid'), ('ST', 'For study')], default='MN', max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_pay_now', models.BooleanField()),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OA', 'On approval'), ('RE', 'Rejected'), ('AC', 'Accepted')], default='OA', max_length=2)),
                ('agreed_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='claims.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='claims.employee')),
            ],
        ),
    ]
